// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentTransactionService.DBContext;

namespace PaymentTransactionService.Migrations
{
    [DbContext(typeof(PaymentTransactionContext))]
    partial class PaymentTransactionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("PaymentTransactionService.Data.PaymentTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserPaymentTransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserPaymentTransactionId");

                    b.ToTable("PaymentTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 1500.0,
                            PaymentDate = new DateTime(2021, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserPaymentTransactionId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 1700.5,
                            PaymentDate = new DateTime(2021, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserPaymentTransactionId = 1L
                        });
                });

            modelBuilder.Entity("PaymentTransactionService.Data.UserPaymentTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountBalance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UserPaymentTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AmountBalance = 30000.0
                        });
                });

            modelBuilder.Entity("PaymentTransactionService.Data.PaymentTransaction", b =>
                {
                    b.HasOne("PaymentTransactionService.Data.UserPaymentTransaction", "UserPaymentTransaction")
                        .WithMany("Transactions")
                        .HasForeignKey("UserPaymentTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPaymentTransaction");
                });

            modelBuilder.Entity("PaymentTransactionService.Data.UserPaymentTransaction", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
